project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "00_intro.qmd"
    - "01_presentation.qmd"

website:
  page-navigation: true
  title: "Quartaki"
  description: "Workshop materials for 1 day workshop on Quarto"
  site-url: "https://drmowinckels.github.io/quartaki/"

  repo-url: https://github.com/drmowinckels/quartaki
  repo-actions: [edit, issue]
  
  navbar:
    background: "#2e3d3d"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/drmowinckels/quartaki
        text: GitHub
    style: docked
    left:
      - href: index.qmd
        text: Home
      - href: 00_intro.qmd
        text: Introduction
      - href: 01_presentation.qmd
        text: Workshop slides
    right:
      - href: https://github.com/drmowinckels
        icon: github
      - href: https://drmowinckels.io
        icon: globe
      - href: https://twitter.com/DrMowinckels
        icon: twitter

format:
  html:
    theme: [cosmo, drmowickel.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    highlight-style: a11y

editor: visual

